[package]
name = "nest"
version = "0.1.0"
authors = ["Benjamin Grange <benjamin.grange@epitech.eu>",
        "Matteo Melis <matteo.melis@epitech.eu>"]

[dependencies]
libc = "0.2.39"
clap = "2.31.1"
ansi_term = "0.11.0"
regex = "0.2.10"
lazy_static = "1.0.0"
libnest = { path = "../libnest" }
