[paths]
cache_dir = "caca"
# download_dir = "/tmp/nest/download/"

# repositories
[repositories.stable]
mirrors = [
    "http://localhost:8000"
]

[repositories.unstable]
mirrors = [
    "olala",
    "isd",
]
